"""Add 'created' and 'updated' fields

Revision ID: 0fc3a22110b8
Revises: 759aa532ee97
Create Date: 2020-09-17 15:30:57.194850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fc3a22110b8'
down_revision = '759aa532ee97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('people', sa.Column('updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'updated')
    op.drop_column('people', 'created')
    # ### end Alembic commands ###
